import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://docs.netlify.com/functions/overview">Netlify Functions on Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://docs.netlify.com/functions/overview/" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Netlify Functions</p>
          </a>

          <a href="https://functions.netlify.com/playground/" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Netlify Playground Functions</p>
          </a>

          <a
            href="https://docs.netlify.com/integrations/frameworks/next-js/overview/"
            className={styles.card}
          >
            <h2>Nextjs on Netlify &rarr;</h2>
            <p>Next.js on Netlify specific docs.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Deploy your Next.js site to a public URL with Netlify.
            </p>
          </a>
        </div>
      </main>
    </div>
  )
}
